name: "Fase 1: Compilador de Kernel 6.18.44 (S905X)"

on:
  workflow_dispatch: # Control 100% manual por botón

jobs:
  build-specific-kernel:
    runs-on: ubuntu-24.04

    steps:
    - name: 1. Descargar este repositorio
      uses: actions/checkout@v4

    - name: 2. Preparar entorno y Compilar Kernel 6.18.44
      run: |
        # 1. Clonamos el framework oficial
        git clone --depth 1 https://github.com/armbian/build armbian-build
        
        # 2. Entramos y ejecutamos la compilación sin sudo y con la placa correcta
        FORCE_BASH_DATA="yes" ./compile.sh \
          BOARD=lepotato \
          BRANCH=edge \
          RELEASE=bookworm \
          BUILD_MINIMAL=yes \
          KERNEL_CONFIGURE=no \
          INSTALL_HEADERS=yes \
          KERNEL_GIT_TAG="v6.18.44" \
          kernel
